import taktil from 'taktil';

import { MaschineButton } from '../controls/MaschineButton';
import { MaschineColorButton } from '../controls/MaschineColorButton';
import { MaschinePanKnob } from '../controls/MaschinePanKnob';
import { RelativeKnob } from '../controls/RelativeKnob';

export const controls = {
    // TOP LEFT
    CHANNEL: new MaschineButton({ status: 0xb0, data1: 0x55 }),
    PLUGIN: new MaschineButton({ status: 0xb0, data1: 0x56 }),
    ARRANGE: new MaschineButton({ status: 0xb0, data1: 0x57 }),
    MIX: new MaschineButton({ status: 0xb0, data1: 0x58 }),
    BROWSE: new MaschineButton({ status: 0xb0, data1: 0x59 }),
    SAMPLING: new MaschineButton({ status: 0xb0, data1: 0x5a }),
    ALL: new MaschineButton({ status: 0xb0, data1: 0x5b }),
    AUTO: new MaschineButton({ status: 0xb0, data1: 0x5c }),
    FS1: new MaschineButton({ status: 0xb0, data1: 0x66 }),
    FS2: new MaschineButton({ status: 0xb0, data1: 0x64 }),

    // METERS
    IN1: new MaschineButton({ status: 0xb0, data1: 0x06 }),
    IN2: new MaschineButton({ status: 0xb0, data1: 0x07 }),
    IN3: new MaschineButton({ status: 0xb0, data1: 0x08 }),
    IN4: new MaschineButton({ status: 0xb0, data1: 0x09 }),
    MST: new MaschineButton({ status: 0xb0, data1: 0x0a }),
    GRP: new MaschineButton({ status: 0xb0, data1: 0x0b }),
    SND: new MaschineButton({ status: 0xb0, data1: 0x0c }),
    CUE: new MaschineButton({ status: 0xb0, data1: 0x0d }),
    KNOB: new taktil.ControlChange({ channel: 0, control: 0x05 }),

    // PERFORMANCE
    TAP: new MaschineButton({ status: 0xb0, data1: 0x6f }),
    STEP_MODE: new MaschineButton({ status: 0xb0, data1: 0x70 }),
    MACRO: new MaschineButton({ status: 0xb0, data1: 0x71 }),
    NOTE_REPEAT: new MaschineButton({ status: 0xb0, data1: 0x72 }),

    // GROUPS
    GROUP_A: new MaschineColorButton({ status: 0xb0, data1: 0x51 }),
    GROUP_B: new MaschineColorButton({ status: 0xb0, data1: 0x52 }),
    GROUP_C: new MaschineColorButton({ status: 0xb0, data1: 0x53 }),
    GROUP_D: new MaschineColorButton({ status: 0xb0, data1: 0x54 }),
    GROUP_E: new MaschineColorButton({ status: 0xb0, data1: 0x5d }),
    GROUP_F: new MaschineColorButton({ status: 0xb0, data1: 0x5e }),
    GROUP_G: new MaschineColorButton({ status: 0xb0, data1: 0x5f }),
    GROUP_H: new MaschineColorButton({ status: 0xb0, data1: 0x60 }),

    // TRANSPORT
    RESTART: new MaschineButton({ status: 0xb0, data1: 0x68 }),
    METRO: new MaschineButton({ status: 0xb0, data1: 0x69 }),
    EVENTS: new MaschineButton({ status: 0xb0, data1: 0x6a }),
    GRID: new MaschineButton({ status: 0xb0, data1: 0x6b }),
    PLAY: new MaschineButton({ status: 0xb0, data1: 0x6c }),
    REC: new MaschineButton({ status: 0xb0, data1: 0x6d }),
    ERASE: new MaschineButton({ status: 0xb0, data1: 0x6e }),

    // MIDDLE
    SCENE: new MaschineButton({ status: 0xb0, data1: 0x73 }),
    PATTERN: new MaschineButton({ status: 0xb0, data1: 0x74 }),
    PAD_MODE: new MaschineButton({ status: 0xb0, data1: 0x75 }),
    NAVIGATE: new MaschineButton({ status: 0xb0, data1: 0x76 }),
    DUPLICATE: new MaschineButton({ status: 0xb0, data1: 0x77 }),
    SELECT: new MaschineButton({ status: 0xb0, data1: 0x78 }),
    SOLO: new MaschineButton({ status: 0xb0, data1: 0x79 }),
    MUTE: new MaschineButton({ status: 0xb0, data1: 0x7a }),

    // PADS
    PAD_1: new MaschineColorButton({ status: 0x90, data1: 0x0c }),
    PAD_2: new MaschineColorButton({ status: 0x90, data1: 0x0d }),
    PAD_3: new MaschineColorButton({ status: 0x90, data1: 0x0e }),
    PAD_4: new MaschineColorButton({ status: 0x90, data1: 0x0f }),
    PAD_5: new MaschineColorButton({ status: 0x90, data1: 0x10 }),
    PAD_6: new MaschineColorButton({ status: 0x90, data1: 0x11 }),
    PAD_7: new MaschineColorButton({ status: 0x90, data1: 0x12 }),
    PAD_8: new MaschineColorButton({ status: 0x90, data1: 0x13 }),
    PAD_9: new MaschineColorButton({ status: 0x90, data1: 0x14 }),
    PAD_10: new MaschineColorButton({ status: 0x90, data1: 0x15 }),
    PAD_11: new MaschineColorButton({ status: 0x90, data1: 0x16 }),
    PAD_12: new MaschineColorButton({ status: 0x90, data1: 0x17 }),
    PAD_13: new MaschineColorButton({ status: 0x90, data1: 0x18 }),
    PAD_14: new MaschineColorButton({ status: 0x90, data1: 0x19 }),
    PAD_15: new MaschineColorButton({ status: 0x90, data1: 0x1a }),
    PAD_16: new MaschineColorButton({ status: 0x90, data1: 0x1b }),

    // EDIT
    COPY: new MaschineButton({ status: 0xb0, data1: 0x41 }),
    PASTE: new MaschineButton({ status: 0xb0, data1: 0x43 }),
    NOTE: new MaschineButton({ status: 0xb0, data1: 0x44 }),
    NUDGE: new MaschineButton({ status: 0xb0, data1: 0x45 }),
    UNDO: new MaschineButton({ status: 0xb0, data1: 0x46 }),
    REDO: new MaschineButton({ status: 0xb0, data1: 0x47 }),
    QUANTIZE: new MaschineButton({ status: 0xb0, data1: 0x48 }),
    CLEAR: new MaschineButton({ status: 0xb0, data1: 0x49 }),
    JOG_DIAL: new RelativeKnob({ channel: 0xb0, control: 0x4a }),
    JOG_BUTTON: new MaschineButton({ status: 0xb0, data1: 0x4b }),
    JOG_RING: new MaschineButton({ status: 0xb0, data1: 0x4c }),
    BACK: new MaschineButton({ status: 0xb0, data1: 0x4d }),
    LEFT_ARROW: new MaschineButton({ status: 0xb0, data1: 0x4e }),
    RIGHT_ARROW: new MaschineButton({ status: 0xb0, data1: 0x4f }),
    ENTER: new MaschineButton({ status: 0xb0, data1: 0x50 }),

    // SCREENS
    ARM_A: new MaschineButton({ status: 0xb7, data1: 0x15 }),
    ARM_B: new MaschineButton({ status: 0xb7, data1: 0x16 }),
    ARM_C: new MaschineButton({ status: 0xb7, data1: 0x17 }),
    ARM_D: new MaschineButton({ status: 0xb7, data1: 0x18 }),
    ARM_E: new MaschineButton({ status: 0xb7, data1: 0x19 }),
    ARM_F: new MaschineButton({ status: 0xb7, data1: 0x1a }),
    ARM_G: new MaschineButton({ status: 0xb7, data1: 0x1b }),
    ARM_H: new MaschineButton({ status: 0xb7, data1: 0x1c }),

    PREV_DEVICE: new MaschineButton({ status: 0xb9, data1: 0x15 }),
    CHILD_DEVICE: new MaschineButton({ status: 0xb9, data1: 0x16 }),
    PARENT_DEVICE: new MaschineButton({ status: 0xb9, data1: 0x17 }),
    NEXT_DEVICE: new MaschineButton({ status: 0xb9, data1: 0x18 }),
    PREV_PARAM_BANK: new MaschineButton({ status: 0xb9, data1: 0x19 }),
    NEXT_PARAM_BANK: new MaschineButton({ status: 0xb9, data1: 0x1c }),

    VOL_TOUCH_A: new MaschineButton({ status: 0xb7, data1: 0x66 }),
    VOL_TOUCH_B: new MaschineButton({ status: 0xb7, data1: 0x68 }),
    VOL_TOUCH_C: new MaschineButton({ status: 0xb7, data1: 0x6a }),
    VOL_TOUCH_D: new MaschineButton({ status: 0xb7, data1: 0x6c }),
    VOL_TOUCH_E: new MaschineButton({ status: 0xb7, data1: 0x6e }),
    VOL_TOUCH_F: new MaschineButton({ status: 0xb7, data1: 0x70 }),
    VOL_TOUCH_G: new MaschineButton({ status: 0xb7, data1: 0x72 }),
    VOL_TOUCH_H: new MaschineButton({ status: 0xb7, data1: 0x74 }),

    VOL_A: new taktil.ControlChange({ channel: 7, control: 0x67 }),
    VOL_B: new taktil.ControlChange({ channel: 7, control: 0x69 }),
    VOL_C: new taktil.ControlChange({ channel: 7, control: 0x6b }),
    VOL_D: new taktil.ControlChange({ channel: 7, control: 0x6d }),
    VOL_E: new taktil.ControlChange({ channel: 7, control: 0x6f }),
    VOL_F: new taktil.ControlChange({ channel: 7, control: 0x71 }),
    VOL_G: new taktil.ControlChange({ channel: 7, control: 0x73 }),
    VOL_H: new taktil.ControlChange({ channel: 7, control: 0x75 }),

    PAN_TOUCH_A: new MaschineButton({ status: 0xb8, data1: 0x66 }),
    PAN_TOUCH_B: new MaschineButton({ status: 0xb8, data1: 0x68 }),
    PAN_TOUCH_C: new MaschineButton({ status: 0xb8, data1: 0x6a }),
    PAN_TOUCH_D: new MaschineButton({ status: 0xb8, data1: 0x6c }),
    PAN_TOUCH_E: new MaschineButton({ status: 0xb8, data1: 0x6e }),
    PAN_TOUCH_F: new MaschineButton({ status: 0xb8, data1: 0x70 }),
    PAN_TOUCH_G: new MaschineButton({ status: 0xb8, data1: 0x72 }),
    PAN_TOUCH_H: new MaschineButton({ status: 0xb8, data1: 0x74 }),

    PAN_A: new MaschinePanKnob({ channel: 8, control: 0x67 }),
    PAN_B: new MaschinePanKnob({ channel: 8, control: 0x69 }),
    PAN_C: new MaschinePanKnob({ channel: 8, control: 0x6b }),
    PAN_D: new MaschinePanKnob({ channel: 8, control: 0x6d }),
    PAN_E: new MaschinePanKnob({ channel: 8, control: 0x6f }),
    PAN_F: new MaschinePanKnob({ channel: 8, control: 0x71 }),
    PAN_G: new MaschinePanKnob({ channel: 8, control: 0x73 }),
    PAN_H: new MaschinePanKnob({ channel: 8, control: 0x75 }),

    // MACRO_TOUCH_1: new MaschineButton({ status: 0xb0, data1: 0x66 }),
    // MACRO_TOUCH_2: new MaschineButton({ status: 0xb0, data1: 0x68 }),
    // MACRO_TOUCH_3: new MaschineButton({ status: 0xb0, data1: 0x6a }),
    // MACRO_TOUCH_4: new MaschineButton({ status: 0xb0, data1: 0x6c }),
    // MACRO_TOUCH_5: new MaschineButton({ status: 0xb0, data1: 0x6e }),
    // MACRO_TOUCH_6: new MaschineButton({ status: 0xb0, data1: 0x70 }),
    // MACRO_TOUCH_7: new MaschineButton({ status: 0xb0, data1: 0x72 }),
    // MACRO_TOUCH_8: new MaschineButton({ status: 0xb0, data1: 0x74 }),

    // MACRO_1: new MaschineButton({ status: 0xb0, data1: 0x67 }),
    // MACRO_2: new MaschineButton({ status: 0xb0, data1: 0x69 }),
    // MACRO_3: new MaschineButton({ status: 0xb0, data1: 0x6b }),
    // MACRO_4: new MaschineButton({ status: 0xb0, data1: 0x6d }),
    // MACRO_5: new MaschineButton({ status: 0xb0, data1: 0x6f }),
    // MACRO_6: new MaschineButton({ status: 0xb0, data1: 0x71 }),
    // MACRO_7: new MaschineButton({ status: 0xb0, data1: 0x73 }),
    // MACRO_8: new MaschineButton({ status: 0xb0, data1: 0x75 }),

    // PARAM_TOUCH_1: new MaschineButton({ status: 0xba, data1: 0x66 }),
    // PARAM_TOUCH_2: new MaschineButton({ status: 0xba, data1: 0x68 }),
    // PARAM_TOUCH_3: new MaschineButton({ status: 0xba, data1: 0x6a }),
    // PARAM_TOUCH_4: new MaschineButton({ status: 0xba, data1: 0x6c }),
    // PARAM_TOUCH_5: new MaschineButton({ status: 0xba, data1: 0x6e }),
    // PARAM_TOUCH_6: new MaschineButton({ status: 0xba, data1: 0x70 }),
    // PARAM_TOUCH_7: new MaschineButton({ status: 0xba, data1: 0x72 }),
    // PARAM_TOUCH_8: new MaschineButton({ status: 0xba, data1: 0x74 }),

    // PARAM_1: new MaschineButton({ status: 0xba, data1: 0x67 }),
    // PARAM_2: new MaschineButton({ status: 0xba, data1: 0x69 }),
    // PARAM_3: new MaschineButton({ status: 0xba, data1: 0x6b }),
    // PARAM_4: new MaschineButton({ status: 0xba, data1: 0x6d }),
    // PARAM_5: new MaschineButton({ status: 0xba, data1: 0x6f }),
    // PARAM_6: new MaschineButton({ status: 0xba, data1: 0x71 }),
    // PARAM_7: new MaschineButton({ status: 0xba, data1: 0x73 }),
    // PARAM_8: new MaschineButton({ status: 0xba, data1: 0x75 }),
};
